server:
  port: 8070

management:
  prometheus:
    metrics:
      export:
        pushgateway:
          base-url: http://prometheus-pushgateway:9091
#          base-url: http://localhost:9091
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show:
        details: always
  endpoints:
    web:
      exposure:
        include:
          - '*'

spring:
  application:
    name: Pastebin-Analytics
  kafka:
    bootstrap-servers: kafka:9092
#    bootstrap-servers: localhost:9092